### ISSUE TITLE
Newer version on roadmap?

### ISSUE THREAD

**Issue by chkpnt** [vaadin/atmosphere#1]
Do you plan to update your fork of the atmosphere-runtime in the near future?

Atmosphere 2.2.8 seems to fix an issue I'm concerning right now: Atmosphere/atmosphere#2014

**Comment by bdunn44** [comment]
I am also interested in an upgrade to 2.3.3 or higher to support Jetty 9.3+. Any roadmap for this? The workaround suggested in the [Atmosphere issue](
https://github.com/Atmosphere/atmosphere/issues/1998) does not work for me.

Related Vaadin forum threads:

[https://vaadin.com/forum#!/thread/10309898](https://vaadin.com/forum#!/thread/10309898)
[https://vaadin.com/forum#!/thread/10746645](https://vaadin.com/forum#!/thread/10746645)

**Comment by lycis** [comment]
I also second this request. Upgrading to 2.3 would fix the NPEs mentioned by @bdunn44. Currently our webapp is running on Jetty 9.2 which we would like to upgrade.

**Comment by Artur-** [comment]
There is 2.2.9.vaadin1 and 2.3.4.vaadin1 in Maven central. You can exclude atmosphere-runtime from the vaadin-push dependency and include one of these to see if it resolves your problem. There is also 2.4.3.vaadin1 in Maven central but that is not API compatible so it requires minor changes to the Vaadin framework code and you cannot simply change the dependency

For Jetty 9.3, https://github.com/Atmosphere/atmosphere/issues/2154 still needs to be resolved. This is tracked in https://dev.vaadin.com/ticket/19742. I'll close this issue so we do not have yet another place to track the same problems
